---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Loading FAS Litters Data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")

# cleaning column names
litters_df = janitor::clean_names(litters_df)
```

## `select`

Choose specific columns (and not others)

```{r}
# specifying a range of columns
select(litters_df, group, gd0_weight:gd_of_birth)

# removing columns
select(litters_df, -gd_of_birth)
```

Renaming columns:

```{r}
select(litters_df, grp = group, lit_num = litter_number)

# dedicated function for renaming that keeps all columns
rename(litters_df, grp = group, lit_num = litter_number)
```

Select helpers:

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
# two ways to move "litter_number" to beginning and keep everything else
select(litters_df, litter_number, everything())
relocate(litters_df, litter_number)
```

## `filter`

Works on rows rather than columns (`select`)

```{r}
# filtering by gd0_weight < 22
filter(litters_df, gd0_weight < 22)

# filtering by gd0_weight >= 22
filter(litters_df, gd0_weight >= 22)
```

```{r}
# filtering by gd_of_birth is equal to 20
filter(litters_df, gd_of_birth == 20)
```

```{r}
# filtering by gd_of_birth is not equal to 20
filter(litters_df, !(gd_of_birth == 20))
filter(litters_df, gd_of_birth != 20)
```

```{r}
# filtering by two conditions
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Con7")
filter(litters_df, group == "Mod8")

# filtering where group is Con7 or Mod8
filter(litters_df, group %in% c("Con7", "Mod8"))
```

## `mutate`

Modifying existing or creating new variables

```{r}
# caclulating a new variable and making everything in group column lowercase
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight, 
  group = str_to_lower(group))
```

